### ISSUE TITLE
Not understanding

### ISSUE THREAD

**Issue by sdorilas** [arcreative/homebridge-xbox-one#2]
I am new to using nodes. I'm currently working with homebridge-Xbox-one. Xbox-on is the only dependency. I've added Xbox one to my accessories in the config file and I have installed the Xbox-on using npm install -g Xbox. Not sure if I'm missing any config files or if I need to do additional steps. However whenever I request to have my Xbox turn on, I see the request through terminal but Xbox never turns on. Any help would be greatly appreciated. Thank you!!!

**Comment by arcreative** [comment]
Closing per https://github.com/arcreative/xbox-on/issues/4
