### ISSUE TITLE
Is anyone else running into an issue with Siri recently?

### ISSUE THREAD

**Issue by BlaydeRunner08** [arcreative/homebridge-xbox-one#6]
I'm not sure where else to post this, but is anyone else experiencing issues with Siri using the plugin?  I use this plugin daily, and usually I have no issues, like below:
![img_2163](https://cloud.githubusercontent.com/assets/25095784/21919608/6fe3f45e-d910-11e6-8727-e9aae65d9db1.PNG)

Recently though, it seems that Siri is now trying to open the Xbox app, even though I've always had it installed and it never confused the two:
![img_2164](https://cloud.githubusercontent.com/assets/25095784/21919609/70016b92-d910-11e6-81ce-376def46fbe7.PNG)

Any thoughts?

**Comment by arcreative** [comment]
Have you tried saying "the Xbox"?

**Comment by arcreative** [comment]
You can alternatively try naming the Xbox something else in your home bridge configuration.

**Comment by BlaydeRunner08** [comment]
I usually do say "the xbox" when I speak to Siri.

I guess I was hoping to have another option than changing the name.  "Xbox" just rolls off the tongue so well, but maybe I'll give "Xbox One" a try.

**Comment by arcreative** [comment]
I tried it again today (I also have the Xbox app) and it still works for me :-/  If you have any other suggestions I'm all ears, but I don't think there's much we can do here...
